{"priority": "major", "kind": "enhancement", "repository": {"links": {"self": {"href": "data/repositories/ignitionrobotics/ign-cmake.json"}, "html": {"href": "#!/ignitionrobotics/ign-cmake"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3e77bcf7-f260-4cec-a1a0-116b8e298901}ts=default"}}, "type": "repository", "name": "ign-cmake", "full_name": "ignitionrobotics/ign-cmake", "uuid": "{3e77bcf7-f260-4cec-a1a0-116b8e298901}"}, "links": {"attachments": {"href": "data/repositories/ignitionrobotics/ign-cmake/issues/58/attachments_page=1.json"}, "self": {"href": "data/repositories/ignitionrobotics/ign-cmake/issues/58.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/ignitionrobotics/ign-cmake/issues/58/watch"}, "comments": {"href": "data/repositories/ignitionrobotics/ign-cmake/issues/58/comments_page=1.json"}, "html": {"href": "#!/ignitionrobotics/ign-cmake/issues/58/provide-check_test_ranpy-script"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/ignitionrobotics/ign-cmake/issues/58/vote"}}, "reporter": {"display_name": "Steve Peters", "uuid": "{2ccfed09-18b8-4921-8d58-15ef01092802}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D"}, "html": {"href": "https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/1fb4816dad9e68337d3096f750951f6cd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSP-1.png"}}, "nickname": "Steven Peters", "type": "user", "account_id": "557058:5de38267-b118-494c-aa76-4fab35448816"}, "title": "Provide check_test_ran.py script", "component": null, "votes": 0, "watches": 1, "content": {"raw": "Currently the ignition packages all have their own check_test_ran.py script, and they have diverged somewhat, with some packages showing tests that fail to run as `Results.test_ran` instead of giving the name of the failing test. This was originally fixed in [gazebo pull request 413](https://bitbucket.org/osrf/gazebo/pull-requests/413/display-name-of-tests-that-dont-run-in/diff) but not propagated. We should consider installing a fixed version of the `check_test_ran.py` script from ign-cmake.\r\n\r\nI am patching some individual scripts now as needed:\r\n\r\n* #!/ignitionrobotics/ign-sensors/pull-requests/50/show-name-for-tests-that-failed-to-run/diff", "markup": "markdown", "html": "<p>Currently the ignition packages all have their own check_test_ran.py script, and they have diverged somewhat, with some packages showing tests that fail to run as <code>Results.test_ran</code> instead of giving the name of the failing test. This was originally fixed in <a data-is-external-link=\"true\" href=\"https://bitbucket.org/osrf/gazebo/pull-requests/413/display-name-of-tests-that-dont-run-in/diff\" rel=\"nofollow\">gazebo pull request 413</a> but not propagated. We should consider installing a fixed version of the <code>check_test_ran.py</code> script from ign-cmake.</p>\n<p>I am patching some individual scripts now as needed:</p>\n<ul>\n<li><a href=\"#!/ignitionrobotics/ign-sensors/pull-requests/50/show-name-for-tests-that-failed-to-run/diff\" rel=\"nofollow\" class=\"ap-connect-link\">#!/ignitionrobotics/ign-sensors/pull-requests/50/show-name-for-tests-that-failed-to-run/diff</a></li>\n</ul>", "type": "rendered"}, "assignee": null, "state": "new", "version": null, "edited_on": null, "created_on": "2019-03-27T18:45:49.467320+00:00", "milestone": null, "updated_on": "2019-03-27T18:45:49.467320+00:00", "type": "issue", "id": 58}