{"links": {"self": {"href": "data/repositories/ignitionrobotics/ign-cmake/issues/55/comments/51318638.json"}, "html": {"href": "#!/ignitionrobotics/ign-cmake/issues/55#comment-51318638"}}, "issue": {"links": {"self": {"href": "data/repositories/ignitionrobotics/ign-cmake/issues/55.json"}}, "type": "issue", "id": 55, "repository": {"links": {"self": {"href": "data/repositories/ignitionrobotics/ign-cmake.json"}, "html": {"href": "#!/ignitionrobotics/ign-cmake"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3e77bcf7-f260-4cec-a1a0-116b8e298901}ts=default"}}, "type": "repository", "name": "ign-cmake", "full_name": "ignitionrobotics/ign-cmake", "uuid": "{3e77bcf7-f260-4cec-a1a0-116b8e298901}"}, "title": "Failing to build Target / does not exist"}, "content": {"raw": "Sure, would love to solve this. \n\nI had a ton of packages that I removed so that I can point the conflict out and recreate the error. I'm making minor edits to the original issue to represent the names of the packages as it is now (changing gazebo_plugins to vgazebo_plugins)\n\nThe vgazebo_plugins package is a package with a couple of executables, and depends on gazebo_plugins which is installed from `apt`. \n\n[Here is the `vgazebo_plugins/CMakeLists.txt` file](https://gist.github.com/tarunuday/d2b5961341096d10163788de7ded8bb8)\n\n[Here is the `gazebo-config.cmake` file](https://gist.github.com/tarunuday/a34a1ac26edc7d933ba0e5f1dfb97cb7)\n\nNot sure if you'd like this but [here is what I get if I do `sudo apt policy *azebo*`](https://gist.github.com/tarunuday/59a153340d5cf6e89928f940ff200b6f). I have no gazebo packages in my ros workspace source. I had installed gazebo_ros_pkgs from source *after* this error started appearing in an attempt to fix it, but it did nothing, and I removed it.", "markup": "markdown", "html": "<p>Sure, would love to solve this. </p>\n<p>I had a ton of packages that I removed so that I can point the conflict out and recreate the error. I'm making minor edits to the original issue to represent the names of the packages as it is now (changing gazebo_plugins to vgazebo_plugins)</p>\n<p>The vgazebo_plugins package is a package with a couple of executables, and depends on gazebo_plugins which is installed from <code>apt</code>. </p>\n<p><a data-is-external-link=\"true\" href=\"https://gist.github.com/tarunuday/d2b5961341096d10163788de7ded8bb8\" rel=\"nofollow\">Here is the <code>vgazebo_plugins/CMakeLists.txt</code> file</a></p>\n<p><a data-is-external-link=\"true\" href=\"https://gist.github.com/tarunuday/a34a1ac26edc7d933ba0e5f1dfb97cb7\" rel=\"nofollow\">Here is the <code>gazebo-config.cmake</code> file</a></p>\n<p>Not sure if you'd like this but <a data-is-external-link=\"true\" href=\"https://gist.github.com/tarunuday/59a153340d5cf6e89928f940ff200b6f\" rel=\"nofollow\">here is what I get if I do <code>sudo apt policy *azebo*</code></a>. I have no gazebo packages in my ros workspace source. I had installed gazebo_ros_pkgs from source <em>after</em> this error started appearing in an attempt to fix it, but it did nothing, and I removed it.</p>", "type": "rendered"}, "created_on": "2019-03-25T16:12:40.815776+00:00", "user": {"display_name": "Tarun Uday", "uuid": "{235f5089-e68c-420d-9ee3-c635fc236da2}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B235f5089-e68c-420d-9ee3-c635fc236da2%7D"}, "html": {"href": "https://bitbucket.org/%7B235f5089-e68c-420d-9ee3-c635fc236da2%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/initials/TU-2.png"}}, "nickname": "tarun.uday", "type": "user", "account_id": "5c93b6f0b44a492c649cfff0"}, "updated_on": "2019-03-25T16:36:41.906979+00:00", "type": "issue_comment", "id": 51318638}