{"links": {"self": {"href": "data/repositories/ignitionrobotics/ign-gazebo/issues/37/comments/53604759.json"}, "html": {"href": "#!/ignitionrobotics/ign-gazebo/issues/37#comment-53604759"}}, "issue": {"links": {"self": {"href": "data/repositories/ignitionrobotics/ign-gazebo/issues/37.json"}}, "type": "issue", "id": 37, "repository": {"links": {"self": {"href": "data/repositories/ignitionrobotics/ign-gazebo.json"}, "html": {"href": "#!/ignitionrobotics/ign-gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{f98d11fe-f287-4dfb-99c3-e2b76a13232e}ts=2082645"}}, "type": "repository", "name": "ign-gazebo", "full_name": "ignitionrobotics/ign-gazebo", "uuid": "{f98d11fe-f287-4dfb-99c3-e2b76a13232e}"}, "title": "Cannot launch on first install on Ubuntu 18.04"}, "content": {"raw": null, "markup": "markdown", "html": "", "type": "rendered"}, "created_on": "2019-08-26T20:25:44.068955+00:00", "user": {"display_name": "Pierre Paques", "uuid": "{4b749cb1-80d5-41e8-a8ee-4dc038a495a0}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B4b749cb1-80d5-41e8-a8ee-4dc038a495a0%7D"}, "html": {"href": "https://bitbucket.org/%7B4b749cb1-80d5-41e8-a8ee-4dc038a495a0%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/fc3778d3f1948ae1ec4c116bb9a29a6ad=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsPP-6.png"}}, "nickname": "ppaques", "type": "user", "account_id": "557058:1c682449-afd8-446f-8a50-370d34854634"}, "updated_on": null, "type": "issue_comment", "id": 53604759}